services:
  - type: web
    name: sielc-po-and-repairs
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python run_migrations.py
    startCommand: gunicorn repair_project.wsgi:application



